// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Device struct {
	DeviceID    string    `json:"device_id"`
	DeviceToken string    `json:"device_token"`
	UserID      string    `json:"user_id"`
	LastUsedAt  time.Time `json:"last_used_at"`
}
