// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Device struct {
	DeviceID    string    `json:"device_id"`
	DeviceToken string    `json:"device_token"`
	UserID      string    `json:"user_id"`
	LastUsedAt  time.Time `json:"last_used_at"`
}

type Notification struct {
	NotificationID   int32     `json:"notification_id"`
	UserID           string    `json:"user_id"`
	SenderID         string    `json:"sender_id"`
	TargetID         int32     `json:"target_id"`
	TargetType       string    `json:"target_type"`
	NotificationType string    `json:"notification_type"`
	Message          string    `json:"message"`
	IsRead           bool      `json:"is_read"`
	CreatedAt        time.Time `json:"created_at"`
}

type PostStatistic struct {
	PostID    int32     `json:"post_id"`
	Views     int64     `json:"views"`
	Likes     int64     `json:"likes"`
	Comments  int64     `json:"comments"`
	Shares    int64     `json:"shares"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	UserID                  string    `json:"user_id"`
	Email                   string    `json:"email"`
	FirstName               string    `json:"first_name"`
	LastName                string    `json:"last_name"`
	About                   *string   `json:"about"`
	Mobile                  *string   `json:"mobile"`
	Address                 *string   `json:"address"`
	AvatarUrl               *string   `json:"avatar_url"`
	BannerUrl               *string   `json:"banner_url"`
	EmailVerified           bool      `json:"email_verified"`
	MobileVerified          bool      `json:"mobile_verified"`
	WizardStep              int32     `json:"wizard_step"`
	WizardCompleted         bool      `json:"wizard_completed"`
	SignupMethod            int32     `json:"signup_method"`
	PracticeArea            *string   `json:"practice_area"`
	PracticeLocation        *string   `json:"practice_location"`
	Experience              *string   `json:"experience"`
	AverageBillingPerClient *int32    `json:"average_billing_per_client"`
	CaseResolutionRate      *int32    `json:"case_resolution_rate"`
	OpenToReferral          bool      `json:"open_to_referral"`
	LicenseVerified         bool      `json:"license_verified"`
	LicenseRejected         bool      `json:"license_rejected"`
	JoinDate                time.Time `json:"join_date"`
}
