// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: notification.sql

package db

import (
	"context"
)

const getDeviceTokenByUserId = `-- name: GetDeviceTokenByUserId :one
SELECT device_token
FROM devices
WHERE user_id = $1
`

func (q *Queries) GetDeviceTokenByUserId(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getDeviceTokenByUserId, userID)
	var device_token string
	err := row.Scan(&device_token)
	return device_token, err
}
