// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: post_statistics.sql

package db

import (
	"context"
)

const incrementComments = `-- name: IncrementComments :exec
INSERT INTO post_statistics (post_id, comments, updated_at)
VALUES ($1, 1, CURRENT_TIMESTAMP)
    ON CONFLICT (post_id)
    DO UPDATE SET comments = post_statistics.comments + 1,
               updated_at = CURRENT_TIMESTAMP
`

func (q *Queries) IncrementComments(ctx context.Context, postID int32) error {
	_, err := q.db.Exec(ctx, incrementComments, postID)
	return err
}

const incrementLikes = `-- name: IncrementLikes :exec
INSERT INTO post_statistics (post_id, likes, updated_at)
VALUES ($1, 1, CURRENT_TIMESTAMP)
    ON CONFLICT (post_id)
    DO UPDATE SET likes = post_statistics.likes + 1,
               updated_at = CURRENT_TIMESTAMP
`

func (q *Queries) IncrementLikes(ctx context.Context, postID int32) error {
	_, err := q.db.Exec(ctx, incrementLikes, postID)
	return err
}
