// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	GetDeviceTokenByUserId(ctx context.Context, userID string) (string, error)
	GetUserNameByUserId(ctx context.Context, userID string) (GetUserNameByUserIdRow, error)
	IncrementComments(ctx context.Context, postID int32) error
	IncrementLikes(ctx context.Context, postID int32) error
}

var _ Querier = (*Queries)(nil)
