// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	GetDeviceTokenByUserId(ctx context.Context, userID string) (string, error)
}

var _ Querier = (*Queries)(nil)
