// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package db

import (
	"context"
)

const getUserNameByUserId = `-- name: GetUserNameByUserId :one
SELECT first_name, last_name
FROM users
WHERE user_id = $1
`

type GetUserNameByUserIdRow struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

func (q *Queries) GetUserNameByUserId(ctx context.Context, userID string) (GetUserNameByUserIdRow, error) {
	row := q.db.QueryRow(ctx, getUserNameByUserId, userID)
	var i GetUserNameByUserIdRow
	err := row.Scan(&i.FirstName, &i.LastName)
	return i, err
}
