apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::021891590100:user/rishukumar.prince@gmail.com
      username: rishukumar.prince@gmail.com
      groups:
        - system:masters