name: Install Prometheus and Grafana

on:
  workflow_dispatch:  # You can trigger this manually, or you can set it to run on a specific event

jobs:
  install-prometheus-grafana:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Set up Kubeconfig
        run: aws eks update-kubeconfig --name legalreferral-notification --region us-east-1

      - name: Create Monitoring Namespace
        run: |
          kubectl get namespace monitoring || kubectl create namespace monitoring

      - name: Add Prometheus Community Helm Repo
        run: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

      - name: Update Helm Repositories
        run: helm repo update

      - name: Install Prometheus and Grafana
        run: |
          helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace \
          --set alertmanager.persistentVolume.storageClass="gp2",server.persistentVolume.storageClass="gp2"
