prometheus:
  prometheusSpec:
    global:
      scrape_interval: 4s
    scrape_configs:
      - job_name: legal-referral-notification
        static_configs:
          - targets: ["legal-referral-notification-service:80"] 